apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-alb
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: "1.8.1"
      helm:
        valueFiles:
          - $values/k8s/charts/alb/values-tools.yaml
    - repoURL: https://github.com/yaseenhamdy/cloud-native-task-manager.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false