apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-test-infra
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/yaseenhamdy/cloud-native-task-manager.git
    targetRevision: HEAD
    path: k8s/infra
  destination:
    name: dev-test-cluster
    namespace: default   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true