apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-ingress-tools
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/yaseenhamdy/cloud-native-task-manager.git
    targetRevision: HEAD
    path: k8s/overlays/tools
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true