apiVersion: v1
kind: ServiceAccount

metadata:
  name: aws-load-balancer-controller

  namespace: kube-system

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::171558409860:role/alb-controller-role