apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-remote-write-auth
  namespace: monitoring
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: prometheus-remote-write-auth
  data:
    - secretKey: username
      remoteRef:
        key: prometheus_secrets
        property: username
    - secretKey: password
      remoteRef:
        key: prometheus_secrets
        property: password