apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-web-config
  namespace: monitoring
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: prometheus-web-config
  data:
    - secretKey: web-config.yaml
      remoteRef:
        key: prometheus_secrets
        property: web-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-datasource-env
  namespace: monitoring
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: prometheus-datasource-env
  data:
    - secretKey: PROM_USER
      remoteRef:
        key: prometheus_secrets
        property: username
    - secretKey: PROM_PASS
      remoteRef:
        key: prometheus_secrets
        property: password