apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: db-external-secret

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore

  target:
    name: db-secrets

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgre_secrets
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgre_secrets
        property: POSTGRES_PASSWORD

    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgre_secrets
        property: POSTGRES_DB

    - secretKey: DATABASE_URL
      remoteRef:
        key: postgre_secrets
        property: DATABASE_URL