apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

namespace: dev


patches:
  - path: flask-deployment-patch.yaml
  - path: react-deployment-patch.yaml
  - path: db-stateful-patch.yaml