name: prod-infra
on: 
  # push:
  #  paths:
  #    - 'terraform/**'
  #  branches:
  #    - main
  #    - feature/multi-eks-cluster
  workflow_dispatch:
  
  workflow_run:
    workflows:
      - shared-infra
    types: [completed]
    branches:
      - main
      - feature/multi-eks-cluster

env:
  AWS_REGION: us-east-1
  TF_VAR_machine_public_IP: ${{secrets.MACHINE_PUBLIC_IP}}
  TF_VAR_bastion_public_key: ${{ secrets.BASTION_PUBLIC_KEY }}

jobs:

 terraform-stage-1:


  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Setup action
      uses: ./.github/actions/terraform-setup
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ${{ env.AWS_REGION }}       
   

    - name: terraform init prod env
      working-directory: ./terraform/environments/prod
      run: terraform init       


    - name: terraform apply prod env (stage 1)
      working-directory: ./terraform/environments/prod
      run: terraform apply -auto-approve -target=module.vpc -var-file=main.tfvars

 terraform-final-stage:

  if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
  runs-on: ubuntu-latest
  needs: terraform-stage-1
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Setup action
      uses: ./.github/actions/terraform-setup
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ${{ env.AWS_REGION }}       
       

    - name: terraform init
      working-directory: ./terraform/environments/prod
      run: terraform init            

    - name: terraform entire apply 
      working-directory: ./terraform/environments/prod
      run: terraform apply -auto-approve -var-file=main.tfvars

  
    